#!/bin/bash

python main.py --model fixed_dose --num_trials 30
python main.py --model wcda --num_trials 30
python main.py --model wpda --num_trials 30
python main.py --model UCBNet --num_trials 30
python main.py --model UCBDNet --num_trials 30
python main.py --model ThompsonNet --R 0.005 --num_trials 30
python main.py --model ThompsonDNet --R 0.005 --num_trials 30
python main.py --model eGreedy --e_0 0.1 --e_scale 1.0 --num_trials 30
python main.py --model eGreedyD --e_0 0.1 --e_scale 1.0 --num_trials 30



python main.py --model fixed_dose --num_trials 3
python main.py --model wcda --num_trials 3
python main.py --model wpda --num_trials 3
python main.py --model UCBNet --num_trials 3
python main.py --model UCBDNet --num_trials 3
python main.py --model ThompsonNet --R 0.005 --num_trials 3
python main.py --model ThompsonDNet --R 0.005 --num_trials 3
python main.py --model eGreedy --e_0 0.1 --e_scale 1.0 --num_trials 3
python main.py --model eGreedyD --e_0 0.1 --e_scale 1.0 --num_trials 3